FROM ubuntu:25.04

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends podman fuse-overlayfs slirp4netns uidmap ca-certificates

RUN echo "ubuntu:1001:64535" > /etc/subuid && \
    echo "ubuntu:1001:64535" > /etc/subgid

ARG _REPO_URL="https://raw.githubusercontent.com/containers/image_build/refs/heads/main/podman"
ADD $_REPO_URL/containers.conf /etc/containers/containers.conf
ADD $_REPO_URL/podman-containers.conf /home/ubuntu/.config/containers/containers.conf

RUN mkdir -p /home/ubuntu/.local/share/containers && \
    chown ubuntu:ubuntu -R /home/ubuntu && \
    chmod 0644 /etc/containers/containers.conf

VOLUME /home/ubuntu/.local/share/containers

# Replace setuid bits by proper file capabilities for uidmap binaries.
# See <https://github.com/containers/podman/discussions/19931>.
RUN apt-get install -y libcap2-bin && \
    chmod 0755 /usr/bin/newuidmap /usr/bin/newgidmap && \
    setcap cap_setuid=ep /usr/bin/newuidmap && \
    setcap cap_setgid=ep /usr/bin/newgidmap && \
    apt-get autoremove --purge -y libcap2-bin

ENV _CONTAINERS_USERNS_CONFIGURED=""

USER ubuntu
WORKDIR /home/ubuntu
